/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package myFirstGradleProject;

public class Library {
	

    public static void main(String[] args) {
    	
    	System.out.println(" ==== api is working =====");
    	
    }
}
